<<<<<<< HEAD   (ca15ad Merge "Merge 3.11.4 into emu-master-dev" into emu-master-dev)
=======
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/api.proto

namespace GPBMetadata\Google\Protobuf;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\SourceContext::initOnce();
        \GPBMetadata\Google\Protobuf\Type::initOnce();
        $pool->internalAddGeneratedFile(
            '
É
google/protobuf/api.protogoogle.protobufgoogle/protobuf/type.proto"
Api
name (	(
methods (2.google.protobuf.Method(
options (2.google.protobuf.Option
version (	6
source_context (2.google.protobuf.SourceContext&
mixins (2.google.protobuf.Mixin\'
syntax (2.google.protobuf.Syntax"Õ
Method
name (	
request_type_url (	
request_streaming (
response_type_url (	
response_streaming ((
options (2.google.protobuf.Option\'
syntax (2.google.protobuf.Syntax"#
Mixin
name (	
root (	Bv
com.google.protobufBApiProtoPZ,google.golang.org/protobuf/types/known/apipb¢GPBªGoogle.Protobuf.WellKnownTypesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

>>>>>>> BRANCH (f82e26 Remove references to stale benchmark data sources.)
