<<<<<<< HEAD   (ca15ad Merge "Merge 3.11.4 into emu-master-dev" into emu-master-dev)
=======
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/duration.proto

namespace GPBMetadata\Google\Protobuf;

class Duration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ë
google/protobuf/duration.protogoogle.protobuf"*
Duration
seconds (
nanos (Bƒ
com.google.protobufBDurationProtoPZ1google.golang.org/protobuf/types/known/durationpbø¢GPBªGoogle.Protobuf.WellKnownTypesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

>>>>>>> BRANCH (f82e26 Remove references to stale benchmark data sources.)
